language: java
jdk:
  - openjdk11
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script: ./gradlew clean build jacocoTestReport coveralls
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -F 'json_file=@build/coveralls/report.json' 'https://coveralls.io/api/v1/jobs'